app_port: 3000
lb_listen_port: 80

# Docker image for demo app
app_image: "nginxdemos/hello:latest"
app_container_name: "demo-app"

# Only HAProxy is allowed to access app_port on app nodes
lb_ip: "192.168.100.18"

# PostgreSQL demo vars (optional)
pg_db: "testdb"
pg_user: "testuser"
pg_pass: "testpass"

# App nodes allowed to connect to Postgres
app_subnet_cidr: "192.168.100.0/24"
